language: scala

script:
  - sbt "++${TRAVIS_SCALA_VERSION}" "^^${SBT_VERSION}" test scripted

jdk: oraclejdk8

matrix:
  include:
  - env: SBT_VERSION="0.13.16"
    scala: 2.10.7
  - env: SBT_VERSION="1.1.4"
    scala: 2.12.5

sudo: false
