language: scala

script:
  - sbt "++${TRAVIS_SCALA_VERSION}" "^^${SBT_VERSION}" relock test scripted

jdk: oraclejdk8

matrix:
  include:
  - env: SBT_VERSION="0.13.16"
    scala: 2.10.6
  - env: SBT_VERSION="1.0.0"
    scala: 2.12.3

sudo: false
